export const pinturaPortugalForuns = [
  'Pintura portuguesa contemporânea',
  'Pintores portugueses emergentes',
  'Grandes mestres da pintura portuguesa',
  'Júlio Pomar e o neo-realismo',
  'Paula Rego e a narrativa visual',
  'Vieira da Silva e a abstração',
  'Amadeo de Souza-Cardoso e o modernismo',
  'Almada Negreiros e a modernidade',
  'José de Guimarães e a arte lusófona',
  'Vhils e a arte urbana portuguesa',
  'Mercado de serigrafias portuguesas',
  'Gravura, litografia e múltiplos',
  'Como avaliar uma pintura portuguesa',
  'Certificados de autenticidade',
  'Molduras e conservação',
  'Restauro de pintura antiga',
  'Restauro de pintura moderna',
  'Coleccionar pintura portuguesa até 500 euros',
  'Coleccionar pintura portuguesa premium',
  'Leilões de arte portuguesa',
  'Galerias de Lisboa',
  'Galerias do Porto',
  'Museus de pintura em Portugal',
  'Pintura e azulejaria',
  'Pintura sacra portuguesa',
  'Pintura histórica portuguesa',
  'Retrato português',
  'Paisagem portuguesa',
  'Marinhas e pintura costeira',
  'Pintura do Douro',
  'Pintura de Lisboa',
  'Pintura do Alentejo',
  'Pintura e tauromaquia',
  'Pintura e literatura portuguesa',
  'Pintura e fado',
  'Pintura e 25 de Abril',
  'Surrealismo português',
  'Abstracionismo português',
  'Neo-realismo português',
  'Naturalismo português',
  'Modernismo português',
  'Arte urbana e pintura expandida',
  'Pintura digital portuguesa',
  'Mulheres pintoras portuguesas',
  'Artistas portugueses na diáspora',
  'Pintura portuguesa em colecções privadas',
  'Pintura portuguesa em museus internacionais',
  'Catálogos raisonné',
  'Bibliografia essencial de pintura portuguesa',
  'Propostas para novas fichas de artistas'
];
