export const pinturaPortugalMarketplace = [
  { artista: 'Júlio Pomar', titulo: 'O Advogado', handle: 'marmore-fernando-pessoa-de-julio-pomar-copia-2', preco: 2500 },
  { artista: 'Júlio Pomar', titulo: 'Corvo', handle: 'marmore-fernando-pessoa-de-julio-pomar-copia-1', preco: 850 },
  { artista: 'Paulo Ferreira', titulo: 'Alfama', handle: 'sintra-original-de-paulo-ferreira-copia', preco: 200 },
  { artista: 'António Segurado', titulo: 'Túnica Branca', handle: 'vortice-cosmico-antonio-segurado-copia', preco: 250 },
  { artista: 'António Segurado', titulo: 'Vórtice Cósmico', handle: 'sem-nome-lll-antonio-segurado-copia', preco: 390 },
  { artista: 'António Segurado', titulo: 'Sem Nome III', handle: 'sem-nome-ll-antonio-segurado-copia', preco: 250 },
  { artista: 'António Segurado', titulo: 'Sem Nome II', handle: 'sem-nome-antonio-segurado-copia', preco: 250 },
  { artista: 'António Segurado', titulo: 'Sem Nome I', handle: 'sem-nome-antonio-segurado', preco: 250 },
  { artista: 'António Neves', titulo: 'Mulheres no Campo', handle: 'cacilheiro-de-lisboa-aguarela-de-antonio-neves-copia', preco: 390 },
  { artista: 'Ricardo Paula', titulo: 'Menina na Praia', handle: 'menina-na-praia-2002', preco: 450 },
  { artista: 'Júlio Pomar', titulo: 'Maternidade Índia II', handle: 'maternidade-india-ii-serigrafia-de-julio-pomar', preco: 399 },
  { artista: 'Joana Rosa', titulo: 'Crianças', handle: 'criancas-de-joana-rosa-copia', preco: 395 },
  { artista: 'Joana Rosa', titulo: 'Bailarinas', handle: '1-bailarinas-de-joana-rosa-copia', preco: 800 },
  { artista: 'Paulo Ferreira', titulo: 'Sintra', handle: 'paulo-ferreira', preco: 450 },
  { artista: 'Mota Urgeiro', titulo: 'Lisboa no Coração', handle: 'oleo-lisboa-no-coracao', preco: 550 },
  { artista: 'Noronha da Costa', titulo: 'Serigrafia de Noronha da Costa', handle: 'serigrafia-de-noronha-da-costa', preco: null },
  { artista: 'José de Guimarães', titulo: 'Serigrafia emoldurada', handle: 'serigrafia-emoldurada-de-jose-de-guimaraes', preco: null },
  { artista: 'Júlio Pomar', titulo: 'Tauromaquia', handle: 'tauromaquia-serigrafia-sobre-tela-de-julio-pomar', preco: null },
  { artista: 'Júlio Pomar', titulo: 'A Águia do Benfica', handle: 'a-aguia-do-benfica-serigrafia-sobre-tela-de-julio-pomar', preco: null },
  { artista: 'Júlio Pomar', titulo: 'Cão', handle: 'cao-belo-original-do-mestre-julio-pomar', preco: null },
  { artista: 'Júlio Resende', titulo: 'Serigrafia de grande dimensão', handle: 'julio-resende-serigrafia-de-grande-dimensao', preco: null },
  { artista: 'António Neves', titulo: 'Eléctricos de Lisboa e Basílica da Estrela', handle: 'electricos-de-lisboa-e-a-basilica-da-estrela', preco: null },
  { artista: 'José de Guimarães', titulo: 'Série Hong Kong', handle: 'serie-hong-kong-serigrafia-de-jose-de-guimaraes', preco: null },
  { artista: 'José de Guimarães', titulo: 'Série Brasil', handle: 'serie-brasil-serigrafia-de-jose-de-guimaraes', preco: null },
  { artista: 'Júlio Pomar', titulo: 'Índia', handle: 'india-serigrafia-do-mestre-julio-pomar', preco: null },
  { artista: 'Oliveira Tavares', titulo: 'Mulher', handle: 'mulher-de-oliveira-tavares', preco: null },
  { artista: 'Pedro Buisel', titulo: 'Além Tejo', handle: 'alem-tejo-serigrafia-de-pedro-buisel', preco: null },
  { artista: 'Júlio Pomar', titulo: 'Três Índias', handle: 'tres-indias-de-julio-pomar', preco: null },
  { artista: 'Júlio Pomar', titulo: 'Camaroeira', handle: 'camaroeira-1958-de-julio-pomar', preco: null },
  { artista: 'Júlio Pomar', titulo: 'Os Pastores', handle: 'os-pastores-asturias-1957-de-julio-pomar', preco: null },
  { artista: 'José de Guimarães', titulo: 'Feitiço Vermelho', handle: 'feitico-vermelho-serigrafia-de-jose-de-guimaraes', preco: null },
  { artista: 'José de Guimarães', titulo: 'Dragão', handle: 'dragao-serigrafia-de-jose-de-guimaraes', preco: null },
  { artista: 'Júlio Pomar', titulo: '25 de Abril', handle: '25-de-abril-obra-do-mestre-julio-pomar', preco: null },
  { artista: 'Manuel Cargaleiro', titulo: 'Grande serigrafia emoldurada', handle: 'grande-serigrafia-do-mestre-cargaleiro-emoldurada', preco: null },
  { artista: 'António Neves', titulo: 'Aveiro', handle: 'aveiro-portugal-aguarela-original-de-antonio-neves', preco: null },
  { artista: 'Almada Negreiros', titulo: 'Sapato, 1963', handle: 'sapato-1963-obra-de-almada-negreiros', preco: null },
  { artista: 'Cruzeiro Seixas', titulo: 'Rara serigrafia antiga II', handle: 'rara-serigrafia-antiga-de-cruzeiro-seixas-ii', preco: null },
  { artista: 'Cruzeiro Seixas', titulo: 'Torre de Belém', handle: 'torre-de-belem-serigrafia-de-cruzeiro-seixas', preco: null },
  { artista: 'José de Guimarães', titulo: 'Série dos Amantes', handle: 'serie-dos-amantes-serigrafia-em-tela-de-jose-de-guimaraes', preco: null },
  { artista: 'Vhils', titulo: 'Looming', handle: 'looming-obra-de-2016-de-vhils', preco: null },
  { artista: 'Nadir Afonso', titulo: 'Serigrafia antiga', handle: 'serigrafia-antiga-de-nadir-afonso', preco: null },
  { artista: 'Joana Rosa', titulo: 'Família e Natal', handle: 'familia-e-natal-serigrafia-de-joana-rosa', preco: null },
  { artista: 'Albino Moura', titulo: 'A Brasileira', handle: 'a-brasileira-serigrafia-de-albino-moura', preco: null },
  { artista: 'Vieira da Silva', titulo: 'Água-forte', handle: 'vieira-da-silva-agua-forte', preco: null },
  { artista: 'Graça Morais', titulo: 'Helena pelas Sete partidas do Mundo', handle: 'helena-pelas-sete-partidas-do-mundo', preco: null },
  { artista: 'Maluda', titulo: 'Alcântara', handle: 'maluda-serigrafia-alcantara', preco: null },
  { artista: 'Manuel Cargaleiro', titulo: 'Natal de Lisboa', handle: 'natal-de-lisboa-de-manuel-cargaleiro', preco: null },
  { artista: 'Vhils', titulo: 'Deplete', handle: 'vhils-deplete-serigrafia', preco: null }
];
