export const pinturaPortugalObrasAtuais02 = [
  'Grande serigrafia emoldurada - Manuel Cargaleiro',
  'Natal de Lisboa - Manuel Cargaleiro',
  'Alcântara - Maluda',
  'Serigrafia de grande dimensão - Júlio Resende',
  'Água-forte - Vieira da Silva',
  'Sapato, 1963 - Almada Negreiros',
  'Torre de Belém - Cruzeiro Seixas',
  'Rara serigrafia antiga II - Cruzeiro Seixas',
  'Maternidade Índia II - Júlio Pomar',
  'Tauromaquia - Júlio Pomar',
  'A Águia do Benfica - Júlio Pomar',
  'Cão - Júlio Pomar',
  'Índia - Júlio Pomar',
  'Três Índias - Júlio Pomar',
  'Camaroeira - Júlio Pomar',
  'Os Pastores - Júlio Pomar',
  '25 de Abril - Júlio Pomar',
  'O Advogado - Júlio Pomar',
  'Corvo - Júlio Pomar',
  'Menina na Praia - Ricardo Paula',
  'Lisboa no Coração - Mota Urgeiro',
  'Serigrafia de Noronha da Costa',
  'Serigrafia emoldurada - José de Guimarães',
  'Obras recentes de Pedro Calapez',
  'Obras recentes de Ana Vidigal'
];
