export const pinturaPortugalMuseus = [
  'Museu Nacional de Arte Antiga - Lisboa',
  'Museu Calouste Gulbenkian - Lisboa',
  'Centro de Arte Moderna Gulbenkian - Lisboa',
  'Museu Nacional de Arte Contemporânea do Chiado - Lisboa',
  'MAAT - Lisboa',
  'Museu de Serralves - Porto',
  'Museu Nacional Soares dos Reis - Porto',
  'Casa das Histórias Paula Rego - Cascais',
  'Museu Grão Vasco - Viseu',
  'Museu Nacional do Azulejo - Lisboa',
  'Museu de Évora - Évora',
  'Museu de Lamego - Lamego',
  'Museu de Aveiro - Aveiro',
  'Museu Nacional Machado de Castro - Coimbra',
  'Museu do Neo-Realismo - Vila Franca de Xira',
  'Fundação Arpad Szenes - Vieira da Silva - Lisboa',
  'Fundação Cupertino de Miranda - Vila Nova de Famalicão',
  'Museu Amadeo de Souza-Cardoso - Amarante',
  'Museu Júlio Pomar - Lisboa',
  'Museu Bordalo Pinheiro - Lisboa',
  'Museu José Malhoa - Caldas da Rainha',
  'Museu Municipal de Faro - Faro',
  'Museu Carlos Machado - Ponta Delgada',
  'Museu de Angra do Heroísmo - Terceira',
  'Museu da Guarda - Guarda',
  'Museu Municipal de Portimão - Portimão',
  'Museu de Alberto Sampaio - Guimarães',
  'Museu Nogueira da Silva - Braga',
  'Museu Abade de Baçal - Bragança',
  'Museu de Arte Contemporânea de Elvas - Elvas',
  'Centro de Arte Oliva - São João da Madeira',
  'Centro Internacional das Artes José de Guimarães - Guimarães',
  'Museu da Cidade - Lisboa',
  'Museu Municipal de Lisboa - Lisboa',
  'Museu do Oriente - Lisboa',
  'Casa-Museu Medeiros e Almeida - Lisboa',
  'Museu do Caramulo - Caramulo',
  'Museu de Arte Sacra do Funchal - Madeira',
  'Museu Henrique e Francisco Franco - Funchal',
  'Museu de Arte Contemporânea da Madeira - Calheta',
  'Museu da Fundação Dionísio Pinheiro - Águeda',
  'Museu Municipal Amadeo de Souza-Cardoso - Amarante',
  'Museu da Misericórdia do Porto - Porto',
  'Museu da Cidade do Porto - Porto',
  'Museu da Chapelaria - São João da Madeira',
  'Museu de Arte Popular - Lisboa',
  'Museu do Traje - Lisboa',
  'Museu da Presidência da República - Lisboa',
  'Palácio Nacional da Ajuda - Lisboa',
  'Palácio Nacional de Sintra - Sintra'
];
