export const pinturaPortugalObrasHistoricas02 = [
  'Cegos de Madrid - Júlio Pomar',
  'A Sopa - Paula Rego',
  'The Dance - Paula Rego',
  'Dog Woman - Paula Rego',
  'Aborto - Paula Rego',
  'A Casa de Celestina - Paula Rego',
  'Retrato de Fernando Pessoa - Carlos Botelho',
  'Lisboa - Carlos Botelho',
  'Cidade Fantástica - Carlos Botelho',
  'A Ribeira - Júlio Resende',
  'Composição Surrealista - António Dacosta',
  'A Festa - António Dacosta',
  'Obras surrealistas - Mário Cesariny',
  'Série surrealista - Cruzeiro Seixas',
  'Composição abstracta - Artur Bual',
  'Painéis cerâmicos - Manuel Cargaleiro',
  'Cidade geométrica - Fernando Lanhas',
  'Composição abstracta - Eduardo Nery',
  'Composição - Joaquim Rodrigo',
  'Pintura gestual - António Palolo',
  'Metamorfose - José Escada',
  'Objecto pictórico - René Bertholo',
  'Retrato - Sarah Afonso',
  'Paisagem - Dordio Gomes',
  'Retrato - Abel Manta'
];
