export const pinturaPortugalObrasAtuais01 = [
  'Looming - Vhils',
  'Deplete - Vhils',
  'Helena pelas Sete partidas do Mundo - Graça Morais',
  'Série dos Amantes - José de Guimarães',
  'Série Brasil - José de Guimarães',
  'Série Hong Kong - José de Guimarães',
  'Feitiço Vermelho - José de Guimarães',
  'Dragão - José de Guimarães',
  'Alfama - Paulo Ferreira',
  'Sintra - Paulo Ferreira',
  'Mulheres no Campo - António Neves',
  'Aveiro - António Neves',
  'Eléctricos de Lisboa e Basílica da Estrela - António Neves',
  'Túnica Branca - António Segurado',
  'Vórtice Cósmico - António Segurado',
  'Sem Nome I - António Segurado',
  'Sem Nome II - António Segurado',
  'Sem Nome III - António Segurado',
  'Crianças - Joana Rosa',
  'Bailarinas - Joana Rosa',
  'Família e Natal - Joana Rosa',
  'Além Tejo - Pedro Buisel',
  'Mulher - Oliveira Tavares',
  'A Brasileira - Albino Moura',
  'Serigrafia antiga - Nadir Afonso'
];
