export const pinturaPortugalEventos = [
  'ARCO Lisboa',
  'Drawing Room Lisboa',
  'Lisboa Art Weekend',
  'Festival Iminente',
  'Bienal de Cerveira',
  'Bienal de Arte Contemporânea de Coimbra',
  'Exposições temporárias da Gulbenkian',
  'Exposições do CAM Gulbenkian',
  'Exposições de Serralves',
  'Exposições do Museu do Chiado',
  'Exposições do MAAT',
  'Exposições da Casa das Histórias Paula Rego',
  'Exposições do Museu Nacional de Arte Antiga',
  'Exposições da Fundação Arpad Szenes - Vieira da Silva',
  'Exposições do Museu Júlio Pomar',
  'Feira do Livro de Arte de Lisboa',
  'Feiras de gravura e serigrafia',
  'Leilões de arte moderna portuguesa',
  'Leilões de arte contemporânea portuguesa',
  'Open studios de artistas portugueses',
  'Roteiro de galerias de Lisboa',
  'Roteiro de galerias do Porto',
  'Exposições da Galeria 111',
  'Exposições da Galeria São Mamede',
  'Exposições da Galeria Cristina Guerra',
  'Exposições da Galeria Filomena Soares',
  'Exposições da Galeria Pedro Cera',
  'Exposições da Galeria Vera Cortês',
  'Exposições da Galeria Belo-Galsterer',
  'Exposições da Underdogs Gallery',
  'Exposições da Appleton',
  'Exposições da Brotéria',
  'Exposições da Galeria Municipal do Porto',
  'Exposições da Galeria Municipal de Lisboa',
  'Exposições do Centro Internacional das Artes José de Guimarães',
  'Exposições do Museu Amadeo de Souza-Cardoso',
  'Exposições do Museu José Malhoa',
  'Exposições do Museu Grão Vasco',
  'Exposições de arte sacra portuguesa',
  'Exposições de pintura moderna portuguesa',
  'Exposições de pintura contemporânea portuguesa',
  'Mostras de jovens artistas portugueses',
  'Prémio Novos Artistas Fundação EDP',
  'Prémios de arte contemporânea portuguesa',
  'Residências artísticas em Portugal',
  'Conferências sobre pintura portuguesa',
  'Visitas guiadas a colecções públicas',
  'Visitas guiadas a colecções privadas',
  'Lançamentos de catálogos de artistas',
  'Encontros de coleccionadores de pintura portuguesa'
];
