export const pinturaPortugalObrasHistoricas01 = [
  'Painéis de São Vicente - Nuno Gonçalves',
  'São Pedro - Grão Vasco',
  'Adoração dos Magos - Grão Vasco',
  'Retrato de D. João VI - Domingos Sequeira',
  'A Morte de Camões - Domingos Sequeira',
  'O Fado - José Malhoa',
  'Os Bêbados - José Malhoa',
  'Camões lendo Os Lusíadas - Columbano Bordalo Pinheiro',
  'Grupo do Leão - Columbano Bordalo Pinheiro',
  'Ceifeiras - Silva Porto',
  'Cabeça de Velha - António Carneiro',
  'A Vida - António Carneiro',
  'Entrada - Amadeo de Souza-Cardoso',
  'Canção Popular - Amadeo de Souza-Cardoso',
  'Coty - Amadeo de Souza-Cardoso',
  'Retrato de Fernando Pessoa - Almada Negreiros',
  'Maternidade - Almada Negreiros',
  'Lusitânia no Bairro Latino - Almada Negreiros',
  'K4 Quadrado Azul - Almada Negreiros',
  'Composição - Vieira da Silva',
  'A Biblioteca - Vieira da Silva',
  'La Gare Inondée - Vieira da Silva',
  'O Almoço do Trolha - Júlio Pomar',
  'Maria da Fonte - Júlio Pomar',
  'Gadanheiro - Júlio Pomar'
];
